# Project configuration
name: calmpanion_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

# SDK constraints
environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_svg: ^2.0.10+1
  lottie: ^2.7.0
  get_storage: ^2.1.1
  get: ^4.6.6

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

# Flutter specific configuration
flutter:
  uses-material-design: true
  
assets:
 - assets/images/
 - assets/animations/
 - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#4A90E2"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
